language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - ~/.npm
script:
  - yarn ci-lint
  - yarn test
  - yarn build
  - yarn build-demo
after_success:
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
